
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSTANT = 10;
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int LEFT = 6;
  public static final int MULTIPLY = 4;
  public static final int VARIABLE = 11;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int LAMBDA = 9;
  public static final int RIGHT = 7;
  public static final int DOT = 8;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "LEFT",
  "RIGHT",
  "DOT",
  "LAMBDA",
  "CONSTANT",
  "VARIABLE"
  };
}

